@urlBase=http://localhost:3001

###GetAll
GET {{urlBase}}/api/persons

###GetByID
GET {{urlBase}}/api/persons/91

###DeleteByID
DELETE {{urlBase}}/api/persons/91

###CreatePerson
POST {{urlBase}}/api/persons
Content-Type: application/json

{
    "name": "Nahuel",
    "number": "1124544412"
}